In [1]:
import json
import pandas as pd
from pathlib import Path

In [17]:
div_folder = Path('../../data/this_project/5_div/')
mapping_fn = div_folder / '5A_metabolomics_name_to_bigg.csv'
mapping_df = pd.read_csv(mapping_fn)

Z_div_folder = Path('../../data/this_project/6_transporterKO/Z_div')
ecmdb_kegg_fn = Z_div_folder / 'C_ecmdb_kegg_ids.csv'

In [20]:
import json

# Load ECMDB JSON and build useful lookup dictionaries
with open('../../data/other/ecmdb.json') as f:
    ecmdb_data = json.load(f)

# ECMDB metabolite ID -> KEGG ID (skip entries missing either field)
ecmdb_id_to_kegg_id = {
    entry['met_id']: entry['kegg_id']
    for entry in ecmdb_data
    if entry.get('met_id') and entry.get('kegg_id')
}

In [ ]:
mapping_df

,Metabolite,BiGG ID,ECMDB ID,ECMDB name,In iML1515,Ecocyc
0,"1,3-diaminopropane",13dampp,NaN,NaN,False,NaN
1,"2,5-dihydroxybenzoate",23dhb,NaN,NaN,True,NaN
2,2-aminoisobutyrate,NaN,ECMDB21403,2-Aminoisobutyric acid,NaN,0.0
3,2-hydroxybutyrate,ghb,ECMDB24007,2-Hydroxybutyric acid,True,NaN
4,2-hydroxyglutaric acid,S2hglut,ECMDB00606,D-2-Hydroxyglutaric acid,True,NaN
...,...,...,...,...,...,...
123,Urocanate,urcan,ECMDB21396,Urocanic acid,False,NaN
124,Valine,val__L,ECMDB00883,L-Valine,True,NaN
125,Xanthine,xan,ECMDB00292,Xanthine,True,NaN
126,Xanthosine,xtsn,ECMDB00299,Xanthosine,True,NaN
127,cAMP,camp,ECMDB00058,Cyclic AMP,True,NaN

In [ ]:
mapping_df['KEGG_ID'] = mapping_df['ECMDB ID'].map(ecmdb_id_to_kegg_id)

In [ ]:
mapping_df.loc[mapping_df['KEGG_ID'].isna(), ['Metabolite', 'BiGG ID', 'ECMDB ID', 'KEGG_ID']].to_csv('temp.csv', index=False)

# Manual curation of the remaining ones that maps

In [ ]:
# KEGG IDs found for metabolites that didn't match in the original lookup.
# Keys match the 'Metabolite' strings exactly as they appear in your CSV.
kegg_id_map = {
    "1,3-diaminopropane": "C00986",
    "2,5-dihydroxybenzoate": "C00628",       
    "2-hydroxybutyrate": "C05984",
    "4-imidazoleacetate": "C02835",
    "Adipate": "C06104",
    "Alpha-aminobutyrate": "C02356",         # NOTE: this is specifically S-2-aminobutyrate
    "Cdp-ethanolamine": "C00570",
    "Creatine": "C00300",
    "Creatinine": "C00791",
    "Hexoses": "C00124",                     # mapped as D-galactose as that is used as C-source
    "Kynurenate": "C01717",
    "Metanephrine": "C05588",
    "Methylguanidine": "C02294",
    "N-acetylleucine": "C02710",
    "Oxoproline": "C01879",                  # 5-Oxo-L-proline (glutathione-pathway form); KEGG also has C02237 for the D-form
    "P-hydroxyphenylacetate": "C00642",
    "Trigonelline ": "C01004",               
}

mapping_df["KEGG_ID"] = mapping_df["KEGG_ID"].fillna(mapping_df["Metabolite"].map(kegg_id_map))

# Map to ecmdb metabolites

In [24]:
ecmdb_kegg_ids = pd.read_csv(ecmdb_kegg_fn, header=None, names=['KEGG_ID'])['KEGG_ID'].tolist()

In [ ]:
mapping_df['IN ECMDB'] = False

for i, row in mapping_df.iterrows():
    ecmdb_id = row['ECMDB ID']
    kegg_id = row['KEGG_ID']

    has_ecmdb_id = isinstance(ecmdb_id, str) and ecmdb_id.startswith('ECMDB')
    has_matching_kegg = isinstance(kegg_id, str) and kegg_id.strip() in ecmdb_kegg_ids

    mapping_df.at[i, 'IN ECMDB'] = has_ecmdb_id or has_matching_kegg

In [ ]:
ecmdb_kegg_ids

['C00109',
 'C00526',
 'C00881',
 'C00141',
 'C01188',
 'C02642',
 'C00120',
 'C00147',
 'C00246',
 'C00033',
 'C00072',
 'C00020',
 'C05402',
 'C00212',
 'C00014',
 'C00185',
 'C00099',
 'C00575',
 'C00164',
 'C00054',
 'C00487',
 'C05512',
 'C00417',
 'C03758',
 'C00429',
 'C01419',
 'C00906',
 'C00063',
 'C00330',
 'C00670',
 'C00475',
 'C00158',
 'C00055',
 'C00114',
 'C00181',
 'C02291',
 'C00559',
 'C01697',
 'C00469',
 'C01233',
 'C00048',
 'C00504',
 'C00031',
 'C00037',
 'C00085',
 'C00051',
 'C00093',
 'C00116',
 'C00242',
 'C00387',
 'C00058',
 'C00124',
 'C00025',
 'C00189',
 'C00198',
 'C00149',
 'C00262',
 'C00082',
 'C00079',
 'C00137',
 'C00041',
 'C00148',
 'C00208',
 'C00155',
 'C00188',
 'C00152',
 'C00159',
 'C00407',
 'C01019',
 'C00122',
 'C00135',
 'C00047',
 'C00243',
 'C00065',
 'C00081',
 'C00186',
 'C00049',
 'C00491',
 'C00294',
 'C00166',
 'C00864',
 'C04006',
 'C01602',
 'C00140',
 'C00006',
 'C01103',
 'C00249',
 'C00036',
 'C00322',
 'C00295',
 'C01185',
 'C03722',
 'C00378',
 'C00163',
 'C00314',
 'C00094',
 'C02191',
 'C00022',
 'C00255',
 'C00931',
 'C00794',
 'C00245',
 'C00042',
 'C00320',
 'C00089',
 'C00178',
 'C00074',
 'C00213',
 'C01005',
 'C00214',
 'C00119',
 'C00121',
 'C00075',
 'C00105',
 'C00366',
 'C00043',
 'C00385',
 'C00700',
 'C00015',
 'C00299',
 'C01762',
 'C00106',
 'C00052',
 'C00483',
 'C05576',
 'C11457',
 'C00196',
 'C02504',
 'C01551',
 'C06423',
 'C03465',
 'C00001',
 'C00156',
 'C00956',
 'C00221',
 'C00062',
 'C00337',
 'C00002',
 'C00305',
 'C00880',
 'C03263',
 'C00097',
 'C00288',
 'C00297',
 'C02630',
 'C02737',
 'C00309',
 'C00257',
 'C00380',
 'C00879',
 'C00064',
 'C00259',
 'C00310',
 'C00070',
 'C00095',
 'C00818',
 'C00416',
 'C00123',
 'C00023',
 'C03196',
 'C00233',
 'C00073',
 'C01179',
 'C08262',
 'C02225',
 'C01157',
 'C05824',
 'C00463',
 'C00884',
 'C00312',
 'C05629',
 'C00392',
 'C04823',
 'C02237',
 'C00438',
 'C19910',
 'C02476',
 'C05021',
 'C03150',
 'C00183',
 'C00003',
 'C00327',
 'C00360',
 'C00565',
 'C02469',
 'C00078',
 'C10438',
 'C00021',
 'C00898',
 'C15571',
 'C02341',
 'C00361',
 'C00448',
 'C00248',
 'C00519',
 'C00234',
 'C01083',
 'C00579',
 'C01137',
 'C00084',
 'C00606',
 'C00458',
 'C04640',
 'C01346',
 'C00224',
 'C00603',
 'C03406',
 'C03460',
 'C03492',
 'C00091',
 'C03232',
 'C00673',
 'C00362',
 'C00669',
 'C00577',
 'C06000',
 'C00415',
 'C00354',
 'C00390',
 'C00357',
 'C03451',
 'C05382',
 'C01944',
 'C11378',
 'C01094',
 'C00275',
 'C04489',
 'C00555',
 'C06505',
 'C01051',
 'C03089',
 'C00136',
 'C04146',
 'C00325',
 'C00169',
 'C01079',
 'C05665',
 'C04501',
 'C00118',
 'C02939',
 'C04352',
 'C00235',
 'C04257',
 'C00108',
 'C00689',
 'C01236',
 'C03090',
 'C00645',
 'C05840',
 'C00053',
 'C01024',
 nan,
 'C01847',
 'C04895',
 'C00430',
 'C01487',
 'C03344',
 'C15672',
 'C00096',
 'C01144',
 'C00546',
 'C00170',
 'C04144',
 'C00083',
 'C00301',
 'C00857',
 'C05932',
 'C00019',
 'C00460',
 'C05356',
 'C03684',
 'C01352',
 'C03415',
 'C00035',
 'C00239',
 'C00024',
 'C00499',
 'C01260',
 'C11437',
 'C05650',
 'C00364',
 'C03287',
 'C00870',
 'C03373',
 'C00705',
 'C00016',
 'C00576',
 'C00352',
 'C00750',
 'C00315',
 'C00232',
 'C01835',
 'C00247',
 'C01168',
 'C00044',
 'C00363',
 'C00100',
 'C00612',
 'C05847',
 'C06257',
 'C01159',
 'C02052',
 'C04322',
 'C00038',
 'C01165',
 'C04376',
 'C00133',
 'C00256',
 'C03546',
 'C00345',
 'C00627',
 'C00842',
 'C03794',
 'C00034',
 'C00154',
 'C00527',
 'C00008',
 'C00459',
 'C01222',
 'C00129',
 'C01529',
 'C00672',
 'C00168',
 'C00204',
 'C00143',
 'C00282',
 'C15587',
 'C04256',
 'C00957',
 'C04281',
 'C00666',
 'C00068',
 'C00882',
 'C04442',
 'C00167',
 'C06427',
 'C00568',
 'C00440',
 'C00144',
 'C11907',
 'C02810',
 'C00092',
 'C05527',
 'C00153',
 'C00365',
 'C00921',
 'C02896',
 'C01134',
 'C01118',
 'C00010',
 'C00067',
 'C00009',
 'C00534',
 'C00179',
 'C00636',
 'C05931',
 'C04734',
 'C00286',
 'C05649',
 'C00059',
 'C16241',
 'C04574',
 'C00111',
 'C00632',
 'C00332',
 'C00004',
 'C00253',
 'C00018',
 'C03069',
 'C00227',
 'C01449',
 'C00329',
 'C04677',
 'C00061',
 'C02593',
 'C01136',
 'C00131',
 'C00250',
 'C00112',
 'C01031',
 'C01180',
 'C00655',
 'C00647',
 'C03479',
 'C03838',
 'C00103',
 'C00101',
 'C00132',
 'C00583',
 'C00184',
 'C02989',
 'C00877',
 'C05100',
 'C00117',
 'C03345',
 'C02714',
 'C19915',
 'C01127',
 'C01417',
 'C00177',
 'C00194',
 'C00490',
 'C01888',
 'C05768',
 'C04644',
 'C00266',
 'C03284',
 'C05924',
 'C05766',
 'C06002',
 'C00263',
 'C01424',
 'C04874',
 'C00894',
 'C00683',
 'C01672',
 'C00209',
 'C15603',
 'C00279',
 'C05332',
 'C01081',
 'C00506',
 'C00088',
 'C00026',
 'C05270',
 'C00244',
 'C02376',
 'C01330',
 'C00979',
 'C00222',
 'C03547',
 'C05999',
 'C00493',
 'C00586',
 'C00032',
 'C01801',
 'C00466',
 'C01050',
 'C00283',
 'C01100',
 'C05688',
 'C05787',
 'C00104',
 'C00217',
 'C00267',
 'C00437',
 'C00533',
 'C00536',
 'C00740',
 'C00793',
 'C00798',
 'C00819',
 'C00831',
 'C00860',
 'C00992',
 'C00993',
 'C01102',
 'C01172',
 'C01204',
 'C01231',
 'C01344',
 'C01353',
 'C01367',
 'C01412',
 'C01563',
 'C01674',
 'C01832',
 'C01909',
 'C02218',
 'C03114',
 'C03221',
 'C04043',
 'C04332',
 'C05172',
 'C04778',
 'C05258',
 'C05260',
 'C05261',
 'C05262',
 'C05263',
 'C05264',
 'C05265',
 'C05266',
 'C05267',
 'C05268',
 'C05269',
 'C05271',
 'C05272',
 'C05273',
 'C05275',
 'C05276',
 'C05345',
 'C05379',
 'C06006',
 'C00900',
 'C00446',
 'C00984',
 'C05771',
 'C05672',
 'C00334',
 'C00719',
 'C00962',
 'C00011',
 'C00501',
 'C00942',
 'C00698',
 'C00853',
 'C06473',
 'C00966',
 'C01216',
 'C01286',
 'C03926',
 'C02637',
 'C00944',
 'C02782',
 'C01304',
 'C04030',
 'C03657',
 'C04171',
 'C03340',
 'C04272',
 'C15556',
 'C04044',
 'C02780',
 'C01345',
 'C01721',
 'C00191',
 'C00258',
 'C03459',
 'C04479',
 'C00130',
 'C00311',
 'C00671',
 'C00476',
 'C01508',
 'C00514',
 'C00828',
 'C11453',
 'C11434',
 'C04579',
 'C00005',
 'C00697',
 'C05811',
 'C05812',
 'C05810',
 'C00007',
 'C07086',
 'C00631',
 'C00988',
 'C00597',
 'C02741',
 'C02739',
 'C00238',
 'C00013',
 'C00861',
 'C04732',
 'C00620',
 'C00199',
 'C00508',
 'C01451',
 'C04411',
 'C01104',
 'C04738',
 'C03733',
 'C04631',
 'C01212',
 'C00692',
 'C04877',
 'C00029',
 'C00086',
 'C00231',
 'C05844',
 'C05921',
 'C14180',
 'C00601',
 'C04751',
 'C00541',
 'C00618',
 'C05699',
 'C03319',
 'C04225',
 'C05259',
 'C05274',
 'C03508',
 'C04133',
 'C00937',
 'C04593',
 'C01250',
 'C00582',
 'C04575',
 'C06196',
 'C00498',
 'C06054',
 'C06055',
 'C06148',
 'C04079',
 'C06010',
 'C05998',
 'C03785',
 'C01097',
 'C02097',
 'C05774',
 'C06508',
 'C01146',
 'C00350',
 'C00344',
 'C05980',
 'C05695',
 'C01528',
 'C05775',
 'C05691',
 'C16336',
 'C16332',
 'C05279',
 'C15647',
 'C02353',
 'C06194',
 'C01151',
 'C01062',
 'C01112',
 'C06007',
 'C04236',
 'C15767',
 'C06509',
 'C06510',
 'C16565',
 'C00251',
 'C04666',
 'C15699',
 'C01267',
 'C02631',
 'C00441',
 'C03082',
 'C04462',
 'C04421',
 'C04896',
 'C04916',
 'C00254',
 'C03972',
 'C14786',
 'C05817',
 'C14793',
 'C14791',
 'C14792',
 'C02909',
 'C16468',
 'C14145',
 'C04349',
 'C14463',
 'C00497',
 'C00522',
 'C03741',
 'C02350',
 'C01302',
 'C11811',
 'C14089',
 'C14806',
 'C14805',
 'C14804',
 'C14803',
 'C14800',
 'C14802',
 'C15668',
 'C15547',
 'C11516',
 'C14865',
 'C14863',
 'C07335',
 'C04691',
 'C03921',
 'C00596',
 'C12624',
 'C11354',
 'C02222',
 'C04752',
 'C14099',
 'C16586',
 'C11436',
 'C16519',
 'C02730',
 'C03160',
 'C14858',
 'C04824',
 'C14848',
 'C04932',
 'C04919',
 'C05923',
 'C12835',
 'C12834',
 'C02355',
 'C11544',
 'C16587',
 'C02512',
 'C14899',
 'C04478',
 'C01187',
 'C04181',
 'C16469',
 'C16272',
 'C16273',
 'C16338',
 'C16334',
 'C02232',
 'C14847',
 'C05822',
 'C05696',
 'C01368',
 'C11435',
 'C04556',
 'C11355',
 'C01279',
 'C04115',
 'C11583',
 'C06762',
 'C03589',
 'C16595',
 'C06056',
 'C03765',
 'C04327',
 'C03393',
 'C14855',
 'C04294',
 'C04051',
 'C01268',
 'C14144',
 'C00679',
 'C04053',
 'C16471',
 'C16470',
 'C01269',
 'C16596',
 'C16466',
 'C01037',
 'C14856',
 'C01092',
 'C06397',
 'C06398',
 'C06735',
 'C06187',
 'C14851',
 'C14852',
 'C07118',
 'C06206',
 'C05378',
 'C00663',
 'C14840',
 'C14839',
 'C04706',
 'C12622',
 'C11588',
 'C04431',
 'C07091',
 'C04121',
 'C05946',
 'C00817',
 'C06032',
 'C00905',
 'C05404',
 'C15930',
 'C06377',
 'C02262',
 'C00333',
 'C02265',
 'C01182',
 'C01380',
 'C05922',
 'C06311',
 'C06114',
 'C05711',
 'C14874',
 'C05730',
 'C04494',
 'C06193',
 'C01228',
 'C03506',
 'C00885',
 'C16186',
 'C01099',
 'C01131',
 'C01101',
 'C03291',
 'C16238',
 'C02995',
 'C00552',
 'C04851',
 'C04302',
 'C06376',
 'C02713',
 'C16698',
 'C02999',
 'C03296',
 'C00802',
 'C00313',
 'C02463',
 'C02876',
 'C14868',
 'C14864',
 'C14861',
 'C14871',
 'C03539',
 'C06188',
 'C00447',
 'C03175',
 'C00748',
 'C05778',
 'C16688',
 'C12623',
 'C12838',
 'C04652',
 'C01170',
 'C04882',
 'C04702',
 'C05892',
 'C00348',
 'C05898',
 'C05893',
 'C05897',
 'C02091',
 'C19771',
 'C03666',
 'C06369',
 'C02287',
 'C04534',
 'C00134',
 'C02532',
 'C15996',
 'C17556',
 'C20396',
 'C16639',
 'C08353',
 'C19909',
 'C06701',
 'C05251',
 'C01177',
 'C16488',
 'C11837',
 'C20750',
 'C18076',
 'C02426',
 'C02216',
 'C18239',
 'C00623',
 'C04346',
 'C06018',
 'C17568',
 'C01337',
 'C05791',
 'C05528',
 'C05686',
 'C05670',
 'C05640',
 'C05519',
 'C05689',
 'C05698',
 'C06026',
 'C00338',
 'C13908',
 'C02912',
 'C02917',
 'C16667',
 'C00718',
 'C04036',
 'C02354',
 'C16699',
 'C04204',
 'C11822',
 'C05818',
 'C05815',
 'C05814',
 'C19975',
 'C20253',
 'C01013',
 'C05809',
 'C16216',
 'C12621',
 'C19945',
 'C05198',
 'C00445',
 'C04454',
 'C02655',
 'C20239',
 'C01300',
 'C04807',
 'C20248',
 'C02130',
 'C05554',
 'C01342',
 'C01413',
 'C00076',
 'C02962',
 'C05385',
 'C11472',
 'C07838',
 'C19882',
 'C00855',
 'C01571',
 'C05925',
 'C00580',
 'C11143',
 'C02679',
 'C11514',
 'C05821',
 'C06229',
 'C06228',
 'C05389',
 'C00127',
 'C02979',
 'C03274',
 'C00080',
 'C01585',
 'C01326',
 'C00027',
 'C05123',
 'C06025',
 'C06024',
 'C12147',
 'C01936',
 'C06232',
 'C18060',
 'C06332',
 'C02983',
 'C01029',
 'C00887',
 'C01444',
 'C01261',
 'C20249',
 'C06501',
 'C00479',
 'C00296',
 'C01007',
 'C04425',
 'C18870',
 'C00412',
 'C00704',
 'C01755',
 'C06022',
 'C16155',
 'C06240',
 'C17569',
 'C20231',
 'C19848',
 'C06697',
 'C04114',
 'C00206',
 'C00688',
 'C07597',
 'C01181',
 'C15700',
 'C01991',
 'C00182',
 'C11145',
 'C01530',
 'C01468',
 'C05684',
 'C01225',
 'C14179',
 'C09306',
 'C16218',
 'C16157',
 'C16153',
 'C16154',
 'C06230',
 'C00770',
 'C03172',
 'C06231',
 'C03619',
 'C10172',
 'C00408',
 'C02823',
 'C04483',
 'C02067',
 'C00150',
 'C00291',
 'C00396',
 'C15473',
 'C01478',
 'C14819',
 'C00785',
 'C02226',
 'C08261',
 'C00715',
 'C01042',
 'C00630',
 'C03665',
 'C03283',
 'C06772',
 'C07190',
 'C02787',
 'C02704',
 'C04423',
 'C06771',
 'C00128',
 'C00346',
 'C01089',
 'C00474',
 'C00712',
 'C00695',
 'C00489',
 'C05607',
 'C06424',
 ...]

In [ ]:
mapping_df.to_csv(mapping_fn, index=False)

# Map KEIO KO metabolomics

In [27]:
data_folder_KEIO_KO = Path('../../data/this_project/2_keio_strains_screening/')

mapping_df2 = pd.read_csv(data_folder_KEIO_KO / '2F_metabolomics_name_to_bigg.csv')

In [28]:
new_mapping_df2 = []

for _, row in mapping_df2.iterrows():
    metabolite = str(row['Metabolite']).strip()
    matched_rows = mapping_df[mapping_df['Metabolite'].astype(str).str.strip() == metabolite]

    if not matched_rows.empty:
        matched_row = matched_rows.iloc[0]
        new_mapping_df2.append({
            'Metabolite': metabolite,
            'BiGG ID': row['BiGG ID'],
            'ECMDB ID': matched_row['ECMDB ID'],
            'KEGG_ID': matched_row['KEGG_ID'],
            'IN ECMDB': matched_row['IN ECMDB'],
            'From Mapping 1': True
        })
    else:
        new_mapping_df2.append({
            'Metabolite': metabolite,
            'BiGG ID': row['BiGG ID'],
            'ECMDB ID': None,
            'KEGG_ID': None,
            'IN ECMDB': False,
            'From Mapping 1': False
        })

new_mapping_df2 = pd.DataFrame(new_mapping_df2)

In [29]:
mapping_df.loc[mapping_df.Metabolite == 'Carnitine (c0)']

Empty DataFrame
Columns: [Metabolite, BiGG ID, ECMDB ID, ECMDB name, In iML1515, Ecocyc, KEGG_ID, IN ECMDB]
Index: []

In [31]:
# KEGG IDs extracted directly from iML1515.xml (BiGG model annotations).
# Keys match the 'Metabolite' strings exactly as they appear in your CSV.
kegg_id_map2 = {
    "Adenosine 3', 5'-cyclic phosphate": "C00575",
    "2-oxobutanoate/acetoacetate": "C00109",       # model: 2-Oxobutanoate (not acetoacetate)
    "Biotin": "C00120",
    "Cadaverine": "C01672",
    "Carnitine (c0)": "C00318",                     # model also cross-refs C00487
    "Choline": "C00114",
    "FAD": "C00016",
    "Glucosamine 6-phosphate": "C00352",
    "Glutathione reduced": "C00051",
    "Histidinol": "C00860",
    "Mannose": "C00159",
    "Pyridoxal": "C00250",
    "Riboflavin": "C00255",
    "Ribose 5-phosphate": "C03736",                 # alpha-anomer specific; C00117 is the generic form
    "Sedoheptulose-7-phopsphate": "C05382",         # matches the typo in your original file
    "Uridine diphosphate glucuronic acid": "C00167",
    "2,5-dihydroxybenzoate": "C00628"
}

kegg_id_to_ecmdb_id = {v: k for k, v in ecmdb_id_to_kegg_id.items()}
ecmdb_id_map2 = {}
for name, kegg_id in kegg_id_map2.items():
    ecmdb_id = kegg_id_to_ecmdb_id.get(kegg_id)
    if ecmdb_id:
        ecmdb_id_map2[name] = ecmdb_id

ecmdb_id_map2["Adenosine 3', 5'-cyclic phosphate"] = "ECMDB00058"
ecmdb_id_map2["Ribose 5-phosphate"] = "ECMDB02033"

In [32]:
for _, row in new_mapping_df2.iterrows():
    metabolite = str(row['Metabolite']).strip()
    if metabolite in kegg_id_map2:
        new_mapping_df2.at[_, 'KEGG_ID'] = kegg_id_map2[metabolite]
        new_mapping_df2.at[_, 'ECMDB ID'] = ecmdb_id_map2.get(metabolite)
    

for i, row in new_mapping_df2.iterrows():
    ecmdb_id = row['ECMDB ID']
    kegg_id = row['KEGG_ID']
    has_ecmdb_id = isinstance(ecmdb_id, str) and ecmdb_id.startswith('ECMDB')
    has_matching_kegg = isinstance(kegg_id, str) and kegg_id.strip() in ecmdb_kegg_ids
    if has_ecmdb_id or has_matching_kegg:
        new_mapping_df2.at[i, 'IN ECMDB'] = True

In [ ]:
mapping_df2.to_csv(data_folder_KEIO_KO / '2F_metabolomics_name_to_bigg.csv')

,Metabolite,BiGG ID,ECMDB ID,KEGG_ID,IN ECMDB,From Mapping 1
0,"1,3-diaminopropane",13dampp,NaN,C00986,False,True
1,"2, 5-dihydroxybenzoate",NaN,None,None,False,False
2,"2,5-dihydroxybenzoate",NaN,None,C00628,False,True
3,2-aminoisobutyrate,NaN,ECMDB21403,C03665,True,True
4,2-hydroxybutyrate,ghb,ECMDB24007,C05984,True,True
...,...,...,...,...,...,...
139,Urocanate,urcan,ECMDB21396,C00785,True,True
140,Valine,val__L,ECMDB00883,C00183,True,True
141,Xanthine,xan,ECMDB00292,C00385,True,True
142,Xanthosine,xtsn,ECMDB00299,C01762,True,True
143,cAMP,camp,ECMDB00058,C00575,True,True